### PR TITLE
Students test

### PR DESCRIPTION
**Pull request by zniwiarzxxx**
tests for students service

### CODE REVIEW

**Comment by zniwiarzxxx** [comment]
@SaintAngeLs i need you to change the github script for test

**Review by SaintAngeLs — CHANGES_REQUESTED** [review]
@zniwiarzxxx Currently I see 77.78% for Students Service, please, try to achieve 80% and more.

**Comment by an2508374** [comment]
I don't know why but we have there many dll files, maybe somewhere .gitignore is missing?

**Comment by SaintAngeLs** [comment]
> I don't know why but we have there many dll files, maybe somewhere .gitignore is missing?

Somehow, general .gitignore is not covering the projects, so there is a point to add the .gitignore to each of the project of the service.

**Comment by zniwiarzxxx** [comment]
current code covrage of student servise is at 89.55%.

**Review by an2508374 — APPROVED** [review]

**Review by SaintAngeLs — APPROVED** [review]

**Pull request merged**
